name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-build-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # ---- Python/Flask backend checks ----
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Flake8
      run: pip install flake8

    - name: Run Flake8 linter
      run: flake8 app.py

    # ---- Node/React frontend build ----
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: npm ci --silent

    - name: Build frontend
      working-directory: ./frontend
      run: npm run build

    # ---- Docker build and (optionally) push ----
    - name: Docker build (multi-stage)
      run: docker build -t duo-flask-react:${{ github.sha }} .

    - name: DockerHub login
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker push (main branch only)
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.DOCKERHUB_USERNAME && secrets.DOCKERHUB_TOKEN }}
      run: |
        docker tag duo-flask-react:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/duo-flask-react:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/duo-flask-react:${{ github.sha }}